version: "3.8"
services:
    #php service
    php:
        container_name: php
        build:
            context: .
            target: php
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 9000:8080

    # Database
    database:
        container_name: database
        image: mysql:8.0
        ports:
            - "3307:3306"
        environment:
#            MYSQL_ROOT_HOST: ${DB_HOST}
            MYSQL_DATABASE: tgcom
            MYSQL_USER: tgcom_root
            MYSQL_PASSWORD: 12345678
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db-data:/var/lib/mysql
    # radis service
    redis:
        container_name:  redis
        image: redis:alpine
        command: redis-server --appendonly yes --requirepass  "secret"
        ports:
            - "6380:6379"
volumes:
    db-data: ~
